name: VitalStrike
version: "${project.version}"
main: stawa.vitalstrike.VitalStrike
api-version: "1.21"
author: stawa
description: A plugin that displays damage indicators when entities or players take damage

commands:
  vitalstrike:
    description: Main command for VitalStrike
    usage: |
      §6VitalStrike Commands:
      §e/vs help §7- Show this help menu
      §e/vs toggle [on|off] §7- Toggle damage indicators on/off
      §e/vs reload §7- Reload the plugin configuration
      §e/vs stats §7- View your combat statistics
      §e/vs leaderboard [damage|combo|average] §7- View top players leaderboard
      §e/vs hologram [on|off] §7- Toggle combo hologram display
    aliases: [vs]
    permission: vitalstrike.use
    permission-message: §cYou don't have permission to use VitalStrike commands!

permissions:
  vitalstrike.use:
    description: Allows using VitalStrike commands
    default: true
  vitalstrike.reload:
    description: Allows reloading the plugin configuration
    default: op
  vitalstrike.stats:
    description: Allows viewing combat statistics
    default: true
  vitalstrike.leaderboard:
    description: Allows viewing the leaderboard
    default: true
  vitalstrike.hologram:
    description: Allows toggling combo hologram display
    default: true
